---
configs:
- id: aaaaaaaa-a003-a017-0000-000000000133
  config:
    name: Smarter - Application Performance
    template: Smarter-ApplicationPerformance.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0010-000000000133
  config:
    name: Smarter - Mobile or Custom App Performance
    template: Smarter-ApplicationPerformance.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0001-000000000133
  config:
    name: Smarter - Service Performance
    template: Smarter-ServicePerformance.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0002-000000000133
  config:
    name: Smarter - Database Performance
    template: Smarter-DatabasePerformance.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0003-000000000133
  config:
    name: Smarter - Browser Monitor Availability
    template: Smarter-BrowserMonitorAvailability.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0004-000000000133
  config:
    name: Smarter - Http Monitor Availability
    template: Smarter-HttpMonitorAvailability.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0005-000000000133
  config:
    name: Smarter - Service Availability
    template: Smarter-ServiceAvailability.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0006-000000000133
  config:
    name: Smarter - Database Success Rate
    template: Smarter-DatabaseSuccessRate.json
    skip: false
  type:
    api: slo    
- id: aaaaaaaa-a003-a017-0007-000000000133
  config:
    name: Optimization - CPU Usage
    template: Optimization-CPUUsage.json
    skip: false
  type:
    api: slo
- id: aaaaaaaa-a003-a017-0008-000000000133
  config:
    name: Optimization - Memory Usage
    template: Optimization-MemoryUsage.json
    skip: false
  type:
    api: slo    
- id: aaaaaaaa-a003-a017-0009-000000000133
  config:
    name: Optimization - Disk Usage
    template: Optimization-DiskUsage.json
    skip: false
  type:
    api: slo
